version: "3.8"
services:
  weather-service:
    container_name: weather-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      - REDIS_HOST=redis
      - MONGO_URI=mongodb://mongodb:27017/weather_db

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongo-data:
